experiment_name: forest_agent_dev
run_name: group_02_steep_crown_focus_16
compartment_id: dom194_demo
patch_id: dom194_full
forest_type: dense_mixed
agent_version: v1
conda_sh: /home/xth/anaconda3/etc/profile.d/conda.sh
conda_env: tcd
work_dir: /home/xth/tcd/test_prediction
input_image: /home/xth/forest_agent_project/outputs/local_refine/local_refine_18_16_20260310_225604/group_02_steep_crown_focus_16/roi_image.tif
output_dir: /home/xth/forest_agent_project/outputs/local_refine/local_refine_18_16_20260310_225604/group_02_steep_crown_focus_16/seg_output
metrics_json: /home/xth/forest_agent_project/outputs/group_02_steep_crown_focus_16/metrics.json
details_csv: /home/xth/forest_agent_project/outputs/group_02_steep_crown_focus_16/details.csv
xiaoban_shp: /home/xth/forest_agent_project/outputs/local_refine/local_refine_18_16_20260310_225604/group_02_steep_crown_focus_16/roi_xiaoban.shp
xiaoban_id_field: XBH
tree_count_field: LMSL
crown_field: PJGF
closure_field: YBD
area_ha_field: MJ_hm2
stage1_script: stage1_segformer_sliding.py
stage2_script: stage2_cellpose_sam_sliding_v2.py
diam_list: 128,256,320
tile: 1536
overlap: 512
tile_overlap: 0.45
bsize: 256
augment: true
iou_merge_thr: 0.24
dem_tif: /mnt/e/Learning_documents/DEM/dem194.tif
slope_tif: null
aspect_tif: null
